#!/usr/bin/env python
from datetime import datetime,timedelta
from col.common.monadic import Maybe
from typing import Callable,Any, Iterator
#from icecream import ic

def convert_to_time_repr(seconds: float):
    return str(timedelta(seconds=seconds))

def convert_to_val(val: str) -> Maybe[int]:
    """Converts a string value to an integer wrapped in a Maybe object.

    If the input string is non-empty and can be converted to an integer,
    it returns a Maybe object containing the integer. If the conversion fails,
    it returns a Maybe object with an error message. If the input string is
    empty or None, it returns a Maybe object containing 0.

    Args:
        val (str): The string value to convert.

    Returns:
        Maybe: A Maybe object containing either the converted integer,
        an error message, or 0.
    """
    if val is not None and len(val) > 0:
        try:
            return Maybe(int(val))
        except Exception as e:
            return Maybe(f"Unable to convert {val} to int", is_ok=False)
    return Maybe(0)


def split_on_fn(delimiter: str) -> Callable[[str], Maybe]:

    def split_on(line: str) -> Maybe:
        if line is not None:
            fields = line.split(delimiter)
            if len(fields) > 1:
                return Maybe(fields)
            return Maybe(fields, is_ok=False)
        return Maybe("String is None", is_ok=False)

    return split_on


def create_splitters(delims: list[str]) -> list[Callable[[str], Maybe]]:
    return [split_on_fn(delim) for delim in delims]





def list_string_fn(lines: list[str], fn: Callable[[str], Any]) -> Any:
    """ Applies a function to each element of a list of strings and extracts a value from the result.

    Args:
      lines: A list of strings to process.
      fn: A function that takes a string and returns an object with a 'val' attribute.

    Returns:
      A list containing all the values extracted from the 'val' attribute of the results generated by applying 'fn' to each line.
"""
    result = []
    list_of_maybes = map(fn, lines)
    return [element for maybe_obj in list_of_maybes for element in maybe_obj.val]



def apply_functions_to_list(strings: list[str], functions: list[Callable[[str], list[str]]]) -> list[str]:
    """
    Applies a list of functions to a list of strings recursively.

    This function takes a list of strings and a list of functions. It applies the first function
    from the list to the list of strings, then recursively applies the remaining functions
    to the result of the previous function's output.

    Parameters:
    strings (list[str]): A list of strings to which functions will be applied.
    functions (list[Callable[[str], list[str]]]): A list of functions that take a string and return a list of strings.

    Returns:
    list[str]: A list of strings resulting from applying the functions to the input list.
    """
    match functions:
        case []:
            return strings
        case [fn, *rest]:
            result = list_string_fn(strings, fn)
            ret2 = apply_functions_to_list(result, rest)
            return ret2


# write docstring for this function.
def apply_delimiter_fn(delimiters: list[str]):
    """
    Creates a function that applies a series of delimiter-based split functions to a given line.

    This function takes a list of delimiters, creates corresponding split functions,
    and returns a new function that, when called with a line, will apply those split functions
    recursively to the line.

    Parameters:
    delimiters (list[str]): A list of delimiter strings used to create the splitter functions.

    Returns:
    Callable[[str], list[str]]: A function that, given a line, returns a list of strings
    resulting from applying the splitter functions.
    """
    splitter_fns = create_splitters(delimiters)
    def apply_fn(line):
        return apply_functions_to_list([line], splitter_fns)
    return apply_fn
