* Some changes

Due to the changes into the frr standard there are change need to be done.


** First
The first line seems to be complete  as in:
#+begin_example
1	M-GHT	Calle Olsen [SZ]        SZ	50+
#+end_example

The problem is that instead of a tab =\t= sign there are places where
its replaced with 8 spaces.
It should be fairly straight forward.

#+begin_example
fn = split_by_fn('\t')
out = fn(line)
if out is no split
  fn_space = split_by_fn('        ')
  out = fn_space(line)

 return out
#+end_example


Now this could be made into a more abstract function.

Think of it as a function that takes a list of delimiters

#+begin_example
make_split_fn('\t','        ',',,,,,,,')
#+end_example

So what does it need to do.

  1) make_split_fns
     - Create a list of split fn

#+begin_example
split_fn::Callable[[str], Maybe]

try_tree_split:: string -> List[split_fn] -> List[string]
   if split_fn is END
      return string
   else
      split_str = try_tree_split (split_fn string)
      (string (next split_fn))
#+end_example

Come on!
First we have
[A B C "D-E"]

Use two delimiters ['\t',"-"] → [fnT,FnM]
Run the fnT(list) ⇢ [A,B,C,"D-E"]

Next we run each item in the list through fnM
$fn(list, fn) \Rightarrow fn(list+1,fn)$


Lets try this

#+NAME: split_on
#+HEADER: :results output raw :exports both  :session split :wrap example
#+begin_src python
  from functools import reduce
  from itertools import islice

  def split_on_fn(delimiter):
    def fun(line):
      return line.split(delimiter)
    return fun


  def split_on_fn_multi(args: list[str] ):
    list_of_fn = [ split_on_fn(delim) for delim in args ]
    return list_of_fn








  def run_list(string, fns, result):
    fn = next(fns, None)
    print(0, string)
    if fn is not None:
      print(1)
      out = fn(string)
      result.append(out)
      for str_var in out:
        run_list(str_var,islice(fns, 1, None), result)

      print(result)
      return out
    else:
      print("End")
      return result






  list_fns = split_on_fn_multi([' ','-'])
  run_list("a b c d-e", iter(list_fns), [])

#+end_src

#+RESULTS: split_on
#+begin_example
0 a b c d-e
1
0 a
End
0 b
End
0 c
End
0 d-e
End
[['a', 'b', 'c', 'd-e']]
#+end_example

** Another problem

Well the next problem is somewhat problematic.
The =Exp= field is either
 - empty
 - Mas
 - 50+
 - 60+
 - 70+
The problem occurs when its empty. Then everything gets shrunk.
The eassiest way is to add if its missing on the first line.

This can be done in [[file:col/common/frr_copy_parser.py::def merge_lines(init: dict, line)->dict:][merge_lines]]
in the =else= clause. If the number of fields are 4 then we need to add a field, but we havent split it?
Shit! Need to rethink!...

The problem is this:

#+begin_example
1	M-GHT	Jörgen Lindwall [SZ]	SZ
1	M-GHT	Calle Olsen [SZ]        SZ	50+
#+end_example

The first line has one less field. Which is not what we want.
And since we are smashing the two lines together we get:
#+begin_example
1	M-GHT	Calle Olsen [SZ]        SZ	50+  6.804 s	1 hrs, 4 m 34.246 s 235w @3.70WKG	758 - 740 - 776	(0) - (0)	2.274
1	M-GHT	Jörgen Lindwall [SZ]	SZ  1 m 2.579 s	1 hrs, 5 m 30.021 s 274w @3.70WKG	704 - 712 - 744	(0) - (0)	2.160
#+end_example

So how do we find a pattern that knows that a field is missing?
We haven't split anything yet, that is done in the next stage.
At this point we have just a string of text.

The best way would be to split the bloody thing before merging.

Ok , that needs a refactoring.
First we need to extend the input to merge_lines, with =splitter_fn=

The next thing is to create a new list that includes the first line
#+begin_example
 user_lst = ['1','apaa',.....]
#+end_example

The next line should be appended to the first

#+begin_example
 user_lst.extend(splitter(line))
 #+end_example

 Now this should be appended to the output_arr...
